default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
# development:
#   adapter: mysql2
#   encoding: utf8
#   database: fire-note_development
#   pool: 5
#   username: root
#   password:
#   socket: /tmp/mysql.sock
